export const moviesCategories = [
  { id: 28, title: 'Ação' },
  { id: 12, title: 'Aventura' },
  { id: 16, title: 'Animação' },
  { id: 35, title: 'Comédia' },
  { id: 80, title: 'Criminal' },
  { id: 99, title: 'Documentário' },
  { id: 18, title: 'Drama' },
  { id: 10751, title: 'Família' },
  { id: 14, title: 'Fantasia' },
  { id: 36, title: 'História' },
  { id: 27, title: 'Terror' },
  { id: 10402, title: 'Musical' },
  { id: 9648, title: 'Mistério' },
  { id: 10749, title: 'Romance' },
  { id: 878, title: 'Ficção Científica' },
  { id: 10770, title: 'Da TV' },
  { id: 53, title: 'Suspense' },
  { id: 10752, title: 'Guerra' },
  { id: 37, title: 'Ocidentais' },
]